### ISSUE TITLE
Knock out unused bower and npm packages

### ISSUE THREAD

**Issue by AndrewNatoli** [OpenCLTBrigade/cmpd-holiday-gift#22]

**Comment by qbunt** [comment]
I'll take a stab at this

**Comment by AndrewNatoli** [comment]
Thanks @qbunt! I'm not sure if anything _can_ be removed... But what I do know is that right now it takes our new volunteers 30-40 minutes of waiting for packages to install before they can get up and running. 😞

**Comment by qbunt** [comment]
I'm hitting the same issue right now actually. I suspect that it's a combination of the number of packages and the amount of RAM allowed inside the Vagrantfile. There's a lot of everything in here 😄

**Comment by qbunt** [comment]
If you have a lot of volunteers, it may be advantageous to package all the dependencies into your own vagrant box and have everyone just install that. There's enough dependencies that the extra time to download. I got the box up and running but I don't see username and password anywhere to log in. Something you can share in public @AndrewNatoli?

**Comment by qbunt** [comment]
Ran out of time for this, happy to jam if I can get into the UI. Cheers!

**Comment by AndrewNatoli** [comment]
Certainly not a bad idea @qbunt, or else just leaving an archive of them around offline. We haven't had to do this recently but it was definitely one of our growing pains starting this project.

The developer account is `developer@codeforcharlotte.org` and `admin`. I should probably put those in the README somewhere... 🙃

Thanks for checking into it!
