### ISSUE TITLE
Add ReCaptcha to registration screen

### ISSUE THREAD

**Issue by AndrewNatoli** [OpenCLTBrigade/cmpd-holiday-gift#23]

**Comment by xRahul** [comment]
Hey.. I'll add recaptcha to the code! Give me a couple of days to go through the code..

**Comment by shubhang-arora** [comment]
I have added Recaptcha to registration screen and made a  [pull request](https://github.com/CodeForCharlotte/cmpd-holiday-gift-backend/pull/25)
