### ISSUE TITLE
Feedback form for nominations

### ISSUE THREAD

**Issue by AndrewNatoli** [OpenCLTBrigade/cmpd-holiday-gift#30]
When viewing the nominations list as an administrator, add a "Review" button to nominations not marked as reviewed.
- Need to make a migration to add a `reviewed` and `approved` flag to the household table. Both integers that default to `0`. Need to add a `reason` (`varchar 255`) field as well.
- Need to include VueStrap :)
- See (hopefully) attached diagram to show the flow of submitting a review.
- If the modal is powered by Vue that would be way cool. From the modal to submitting / updating the record.

![feedbackform](https://cloud.githubusercontent.com/assets/4162073/19710451/5b017b6c-9afc-11e6-8bbc-f6d29eff7f6f.png)

**Comment by Jillzey** [comment]
I also think a delete functionality would be good for half entered and duplicate nominations.

**Comment by AndrewNatoli** [comment]
@Jillzey For now marketing as "duplicate" will have a similar effect. We can handle legitimately deleting in the future.

**Comment by AndrewNatoli** [comment]
Finished in v1.1.0
