### ISSUE TITLE
Additions to the admin dashboard to track totals

### ISSUE THREAD

**Issue by Jillzey** [OpenCLTBrigade/cmpd-holiday-gift#40]
This is only for admin users. Addition of the dashboard Quick Overview:

Total number of families nominated: 
Number of families approved:
Number of families not approved:

Total number of children nominated:
Number of children approved:
Number of children not approved:

Number of nominations per organization:

The organization groups would be CMS, CMPD, CFD, Other Partners.

**Comment by AtnNn** [comment]
Implemented in the `dashboard_stats` branch. Only tested in sqlite.

![delme](https://cloud.githubusercontent.com/assets/706854/20951851/616990c8-bbf6-11e6-8396-55a995a7d603.png)

**Comment by AndrewNatoli** [comment]
Tested in MySQL
