### ISSUE TITLE
Packing Slip Generation Functionality Added

### ISSUE THREAD

**Issue by Jillzey** [OpenCLTBrigade/cmpd-holiday-gift#45]
As CMPD prepares to fulfill each families Christmas gift a packing slip is generated for each family. This is attached to the outside of their box to make packing easier. This is the current packing slip looks like: (https://drive.google.com/file/d/0B-uZvu8v1mnzUksyaG1sZ1FMZWs/view)

Desired appearance: Can look just like the current one. 
Desired information: All information gathered on the current packing slip. With the addition of the family number. 
Functionality: Pull information out of database to generate packing slip. One slip per approved nomination form.

**Comment by AtnNn** [comment]
Initial support for packing slips is available in `develop`. It should be good enough to merge.

Sample: [Packing Slip.pdf](https://github.com/CodeForCharlotte/cmpd-holiday-gift-backend/files/621534/Packing.Slip.pdf)

**Comment by AndrewNatoli** [comment]
Merged in 1.2.0 

Closing this ticket-- feedback can be addressed in separate tickets
