### ISSUE TITLE
Add Select Middle Schools to Database of Schools

### ISSUE THREAD

**Issue by Jillzey** [OpenCLTBrigade/cmpd-holiday-gift#53]
Select middle schools need to be added to the database, ASAP.  They need to be selectable for user affiliation and in child nomination form. 

Here is an attached file with the list of schools:
[CMS School List.xlsx](https://github.com/CodeForCharlotte/cmpd-holiday-gift-backend/files/632161/CMS.School.List.xlsx)

**Comment by AndrewNatoli** [comment]
@Jillzey Let's rendezvous on this in a bit tonight.. @AtnNn and I added some schools last week but all of the ones in this excel sheet might not be there...

**Comment by AndrewNatoli** [comment]
Waiting on refined list back
