### ISSUE TITLE
User nomination number fixed

### ISSUE THREAD

**Issue by Jillzey** [OpenCLTBrigade/cmpd-holiday-gift#57]
All users are set to default at 5 nominations.  Admins are supposed to be able to increase this number by going into the user account and editting it.  When an admin does this it allows them to change the number in that field but it doesn't save the update. 

This needs to be fixed. Default setting is to remain the same but admins must be able to increase the number of nominations a user can input.

**Comment by AtnNn** [comment]
I believe this was fixed in ef624d3.

Does changing the max number of nominations still not work?

**Comment by AtnNn** [comment]
Fixed
